C

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,13 +35,19 @@ jobs:
           name: Install awscli
           command: |
             curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            if [ -f awscliv2.zip ]; then
-              unzip awscliv2.zip
-              sudo ./aws/install
-            else
+            if [ $? -ne 0 ]; then
               echo "Failed to download AWS CLI package."
               exit 1
             fi
+            unzip awscliv2.zip
+            if [ $? -ne 0 ]; then
+              echo "Failed to unzip AWS CLI package."
+              exit 1
+            fi
+            sudo ./aws/install
+      - run:
+          name: Verify AWS CLI installation
+          command: aws --version
       - run:
           name: Deploy to S3
           command: aws s3 cp myapp.tar.gz s3://${S3_BUCKET_NAME}/
