C

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,8 +29,13 @@ jobs:
           name: Install awscli
           command: |
             curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+            if [ -f awscliv2.zip ]; then
+              unzip awscliv2.zip
+              sudo ./aws/install
+            else
+              echo "Failed to download AWS CLI package."
+              exit 1
+            fi
       - run:
           name: Upload to S3
           command: aws s3 cp myapp.tar.gz s3://${S3_BUCKET_NAME}/
